name: Atualizar Badge de Progresso

on:
  push:
    branches:
      - main 

jobs:
  updateBadge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Atualizar Badge de Progresso
        run: |             
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
